version: '3.8'

services:
  accountopening:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      # Override Alloy settings via environment variables
      - Alloy__ApiKey=${ALLOY_API_KEY:-default_value}
      - Alloy__BaseUrl=${ALLOY_BASE_URL:-https://sandbox.alloy.co/v1/}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: accountopening-network
